name: appsstor
description: "Apps Store."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.1.2
  dio: ^5.9.1
  firebase_core: ^4.4.0
  flutter:
    sdk: flutter
  google_fonts: ^8.0.0
  http: ^1.6.0
  open_file: ^3.5.11
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  share_plus: ^12.0.1
  url_launcher: ^6.3.2
  device_apps: ^2.2.0
  provider: ^6.1.2
  shimmer: ^3.0.0
  flutter_animate: ^4.5.2
  lottie: ^3.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/data/apps.json
    - assets/icon.png


